package internal

import (
    "strings"

    "github.com/JJnvn/Software-Arch-CPRoom/backend/services/room/models"
    "github.com/google/uuid"

    "github.com/gofiber/fiber/v2"
)

type RoomHandler struct {
	service RoomService
}

func NewRoomHandler(service *roomService) *RoomHandler {
	return &RoomHandler{service: service}
}

func (h *RoomHandler) RegisterRoutes(app *fiber.App) {
	app.Get("/rooms", h.ListRooms)
	app.Get("/rooms/:id", h.GetRoom)
	app.Post("/rooms", h.CreateRoom)
	app.Put("/rooms/:id", h.UpdateRoom)
	app.Delete("/rooms/:id", h.DeleteRoom)
}

func (h *RoomHandler) CreateRoom(c *fiber.Ctx) error {
    type reqBody struct {
        Name     string   `json:"name"`
        Capacity int      `json:"capacity"`
        Features []string `json:"features"`
    }

    var req reqBody
    if err := c.BodyParser(&req); err != nil {
        return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"error": "invalid request"})
    }
    if len(strings.TrimSpace(req.Name)) == 0 {
        return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"error": "name is required"})
    }
    if req.Capacity < 0 {
        return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"error": "capacity must be >= 0"})
    }

    room := models.Room{ // ID autogenerated by DB
        Name:     strings.TrimSpace(req.Name),
        Capacity: req.Capacity,
        Features: models.StringList(req.Features),
    }

    if err := h.service.Create(&room); err != nil {
        // Handle unique constraint violation (Postgres code 23505)
        if strings.Contains(strings.ToLower(err.Error()), "duplicate key") || strings.Contains(err.Error(), "23505") {
            return c.Status(fiber.StatusConflict).JSON(fiber.Map{"error": "room name already exists"})
        }
        return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{"error": err.Error()})
    }
    return c.Status(fiber.StatusCreated).JSON(room)
}

func (h *RoomHandler) UpdateRoom(c *fiber.Ctx) error {
	var room models.Room
	if err := c.BodyParser(&room); err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "invalid request",
		})
	}

	idStr := c.Params("id")
	uid, err := uuid.Parse(idStr)
	if err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "invalid UUID format",
		})
	}

	room.ID = uid
	if err := h.service.Update(&room); err != nil {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
			"error": err.Error(),
		})
	}

	return c.JSON(room)
}

func (h *RoomHandler) DeleteRoom(c *fiber.Ctx) error {
	idStr := c.Params("id")
	id, err := uuid.Parse(idStr)
	if err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "invalid UUID format",
		})
	}

	if err := h.service.Delete(id); err != nil {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
			"error": err.Error(),
		})
	}

	return c.SendStatus(fiber.StatusNoContent)
}

func (h *RoomHandler) GetRoom(c *fiber.Ctx) error {
	idStr := c.Params("id")

	id, err := uuid.Parse(idStr)
	if err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"error": "invalid UUID format"})
	}

	room, err := h.service.GetByID(id)
	if err != nil {
		return c.Status(fiber.StatusNotFound).JSON(fiber.Map{"error": "room not found"})
	}
	return c.JSON(room)
}

func (h *RoomHandler) ListRooms(c *fiber.Ctx) error {
	rooms, err := h.service.List()
	if err != nil {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{"error": err.Error()})
	}
	return c.JSON(rooms)
}
