// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: approval.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApprovalService_ListPending_FullMethodName      = "/approval.ApprovalService/ListPending"
	ApprovalService_ApproveBooking_FullMethodName   = "/approval.ApprovalService/ApproveBooking"
	ApprovalService_DenyBooking_FullMethodName      = "/approval.ApprovalService/DenyBooking"
	ApprovalService_ReassignApprover_FullMethodName = "/approval.ApprovalService/ReassignApprover"
	ApprovalService_GetAuditTrail_FullMethodName    = "/approval.ApprovalService/GetAuditTrail"
)

// ApprovalServiceClient is the client API for ApprovalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApprovalServiceClient interface {
	ListPending(ctx context.Context, in *ListPendingRequest, opts ...grpc.CallOption) (*ListPendingResponse, error)
	ApproveBooking(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*ApproveResponse, error)
	DenyBooking(ctx context.Context, in *DenyRequest, opts ...grpc.CallOption) (*DenyResponse, error)
	ReassignApprover(ctx context.Context, in *ReassignRequest, opts ...grpc.CallOption) (*ReassignResponse, error)
	GetAuditTrail(ctx context.Context, in *GetAuditTrailRequest, opts ...grpc.CallOption) (*AuditTrailResponse, error)
}

type approvalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApprovalServiceClient(cc grpc.ClientConnInterface) ApprovalServiceClient {
	return &approvalServiceClient{cc}
}

func (c *approvalServiceClient) ListPending(ctx context.Context, in *ListPendingRequest, opts ...grpc.CallOption) (*ListPendingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingResponse)
	err := c.cc.Invoke(ctx, ApprovalService_ListPending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) ApproveBooking(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*ApproveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveResponse)
	err := c.cc.Invoke(ctx, ApprovalService_ApproveBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) DenyBooking(ctx context.Context, in *DenyRequest, opts ...grpc.CallOption) (*DenyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DenyResponse)
	err := c.cc.Invoke(ctx, ApprovalService_DenyBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) ReassignApprover(ctx context.Context, in *ReassignRequest, opts ...grpc.CallOption) (*ReassignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReassignResponse)
	err := c.cc.Invoke(ctx, ApprovalService_ReassignApprover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) GetAuditTrail(ctx context.Context, in *GetAuditTrailRequest, opts ...grpc.CallOption) (*AuditTrailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditTrailResponse)
	err := c.cc.Invoke(ctx, ApprovalService_GetAuditTrail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApprovalServiceServer is the server API for ApprovalService service.
// All implementations must embed UnimplementedApprovalServiceServer
// for forward compatibility.
type ApprovalServiceServer interface {
	ListPending(context.Context, *ListPendingRequest) (*ListPendingResponse, error)
	ApproveBooking(context.Context, *ApproveRequest) (*ApproveResponse, error)
	DenyBooking(context.Context, *DenyRequest) (*DenyResponse, error)
	ReassignApprover(context.Context, *ReassignRequest) (*ReassignResponse, error)
	GetAuditTrail(context.Context, *GetAuditTrailRequest) (*AuditTrailResponse, error)
	mustEmbedUnimplementedApprovalServiceServer()
}

// UnimplementedApprovalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApprovalServiceServer struct{}

func (UnimplementedApprovalServiceServer) ListPending(context.Context, *ListPendingRequest) (*ListPendingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPending not implemented")
}
func (UnimplementedApprovalServiceServer) ApproveBooking(context.Context, *ApproveRequest) (*ApproveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveBooking not implemented")
}
func (UnimplementedApprovalServiceServer) DenyBooking(context.Context, *DenyRequest) (*DenyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DenyBooking not implemented")
}
func (UnimplementedApprovalServiceServer) ReassignApprover(context.Context, *ReassignRequest) (*ReassignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReassignApprover not implemented")
}
func (UnimplementedApprovalServiceServer) GetAuditTrail(context.Context, *GetAuditTrailRequest) (*AuditTrailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuditTrail not implemented")
}
func (UnimplementedApprovalServiceServer) mustEmbedUnimplementedApprovalServiceServer() {}
func (UnimplementedApprovalServiceServer) testEmbeddedByValue()                         {}

// UnsafeApprovalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApprovalServiceServer will
// result in compilation errors.
type UnsafeApprovalServiceServer interface {
	mustEmbedUnimplementedApprovalServiceServer()
}

func RegisterApprovalServiceServer(s grpc.ServiceRegistrar, srv ApprovalServiceServer) {
	// If the following call pancis, it indicates UnimplementedApprovalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApprovalService_ServiceDesc, srv)
}

func _ApprovalService_ListPending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).ListPending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_ListPending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).ListPending(ctx, req.(*ListPendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_ApproveBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).ApproveBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_ApproveBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).ApproveBooking(ctx, req.(*ApproveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_DenyBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DenyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).DenyBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_DenyBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).DenyBooking(ctx, req.(*DenyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_ReassignApprover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReassignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).ReassignApprover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_ReassignApprover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).ReassignApprover(ctx, req.(*ReassignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_GetAuditTrail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditTrailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).GetAuditTrail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_GetAuditTrail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).GetAuditTrail(ctx, req.(*GetAuditTrailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApprovalService_ServiceDesc is the grpc.ServiceDesc for ApprovalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApprovalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "approval.ApprovalService",
	HandlerType: (*ApprovalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPending",
			Handler:    _ApprovalService_ListPending_Handler,
		},
		{
			MethodName: "ApproveBooking",
			Handler:    _ApprovalService_ApproveBooking_Handler,
		},
		{
			MethodName: "DenyBooking",
			Handler:    _ApprovalService_DenyBooking_Handler,
		},
		{
			MethodName: "ReassignApprover",
			Handler:    _ApprovalService_ReassignApprover_Handler,
		},
		{
			MethodName: "GetAuditTrail",
			Handler:    _ApprovalService_GetAuditTrail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "approval.proto",
}
