// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: approval.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingRequest) Reset() {
	*x = ListPendingRequest{}
	mi := &file_approval_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingRequest) ProtoMessage() {}

func (x *ListPendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_approval_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingRequest.ProtoReflect.Descriptor instead.
func (*ListPendingRequest) Descriptor() ([]byte, []int) {
	return file_approval_proto_rawDescGZIP(), []int{0}
}

func (x *ListPendingRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

type ListPendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pending       []*PendingBooking      `protobuf:"bytes,1,rep,name=pending,proto3" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingResponse) Reset() {
	*x = ListPendingResponse{}
	mi := &file_approval_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingResponse) ProtoMessage() {}

func (x *ListPendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_approval_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingResponse.ProtoReflect.Descriptor instead.
func (*ListPendingResponse) Descriptor() ([]byte, []int) {
	return file_approval_proto_rawDescGZIP(), []int{1}
}

func (x *ListPendingResponse) GetPending() []*PendingBooking {
	if x != nil {
		return x.Pending
	}
	return nil
}

type PendingBooking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingBooking) Reset() {
	*x = PendingBooking{}
	mi := &file_approval_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingBooking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingBooking) ProtoMessage() {}

func (x *PendingBooking) ProtoReflect() protoreflect.Message {
	mi := &file_approval_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingBooking.ProtoReflect.Descriptor instead.
func (*PendingBooking) Descriptor() ([]byte, []int) {
	return file_approval_proto_rawDescGZIP(), []int{2}
}

func (x *PendingBooking) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *PendingBooking) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PendingBooking) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PendingBooking) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *PendingBooking) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type ApproveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	StaffId       string                 `protobuf:"bytes,2,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequest) Reset() {
	*x = ApproveRequest{}
	mi := &file_approval_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequest) ProtoMessage() {}

func (x *ApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_approval_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequest) Descriptor() ([]byte, []int) {
	return file_approval_proto_rawDescGZIP(), []int{3}
}

func (x *ApproveRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *ApproveRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

type ApproveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveResponse) Reset() {
	*x = ApproveResponse{}
	mi := &file_approval_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveResponse) ProtoMessage() {}

func (x *ApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_approval_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveResponse.ProtoReflect.Descriptor instead.
func (*ApproveResponse) Descriptor() ([]byte, []int) {
	return file_approval_proto_rawDescGZIP(), []int{4}
}

func (x *ApproveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DenyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	StaffId       string                 `protobuf:"bytes,2,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyRequest) Reset() {
	*x = DenyRequest{}
	mi := &file_approval_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyRequest) ProtoMessage() {}

func (x *DenyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_approval_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyRequest.ProtoReflect.Descriptor instead.
func (*DenyRequest) Descriptor() ([]byte, []int) {
	return file_approval_proto_rawDescGZIP(), []int{5}
}

func (x *DenyRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *DenyRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *DenyRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DenyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyResponse) Reset() {
	*x = DenyResponse{}
	mi := &file_approval_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyResponse) ProtoMessage() {}

func (x *DenyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_approval_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyResponse.ProtoReflect.Descriptor instead.
func (*DenyResponse) Descriptor() ([]byte, []int) {
	return file_approval_proto_rawDescGZIP(), []int{6}
}

func (x *DenyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReassignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	NewStaffId    string                 `protobuf:"bytes,2,opt,name=new_staff_id,json=newStaffId,proto3" json:"new_staff_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReassignRequest) Reset() {
	*x = ReassignRequest{}
	mi := &file_approval_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReassignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReassignRequest) ProtoMessage() {}

func (x *ReassignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_approval_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReassignRequest.ProtoReflect.Descriptor instead.
func (*ReassignRequest) Descriptor() ([]byte, []int) {
	return file_approval_proto_rawDescGZIP(), []int{7}
}

func (x *ReassignRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *ReassignRequest) GetNewStaffId() string {
	if x != nil {
		return x.NewStaffId
	}
	return ""
}

type ReassignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReassignResponse) Reset() {
	*x = ReassignResponse{}
	mi := &file_approval_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReassignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReassignResponse) ProtoMessage() {}

func (x *ReassignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_approval_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReassignResponse.ProtoReflect.Descriptor instead.
func (*ReassignResponse) Descriptor() ([]byte, []int) {
	return file_approval_proto_rawDescGZIP(), []int{8}
}

func (x *ReassignResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetAuditTrailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditTrailRequest) Reset() {
	*x = GetAuditTrailRequest{}
	mi := &file_approval_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditTrailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditTrailRequest) ProtoMessage() {}

func (x *GetAuditTrailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_approval_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditTrailRequest.ProtoReflect.Descriptor instead.
func (*GetAuditTrailRequest) Descriptor() ([]byte, []int) {
	return file_approval_proto_rawDescGZIP(), []int{9}
}

func (x *GetAuditTrailRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type AuditTrailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AuditEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditTrailResponse) Reset() {
	*x = AuditTrailResponse{}
	mi := &file_approval_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditTrailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditTrailResponse) ProtoMessage() {}

func (x *AuditTrailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_approval_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditTrailResponse.ProtoReflect.Descriptor instead.
func (*AuditTrailResponse) Descriptor() ([]byte, []int) {
	return file_approval_proto_rawDescGZIP(), []int{10}
}

func (x *AuditTrailResponse) GetEvents() []*AuditEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type AuditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	BookingId     string                 `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	StaffId       string                 `protobuf:"bytes,3,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"` // approve/deny/reassign
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_approval_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_approval_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_approval_proto_rawDescGZIP(), []int{11}
}

func (x *AuditEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AuditEvent) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *AuditEvent) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *AuditEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuditEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_approval_proto protoreflect.FileDescriptor

const file_approval_proto_rawDesc = "" +
	"\n" +
	"\x0eapproval.proto\x12\bapproval\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n" +
	"\x12ListPendingRequest\x12\x19\n" +
	"\bstaff_id\x18\x01 \x01(\tR\astaffId\"I\n" +
	"\x13ListPendingResponse\x122\n" +
	"\apending\x18\x01 \x03(\v2\x18.approval.PendingBookingR\apending\"\xc1\x01\n" +
	"\x0ePendingBooking\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x120\n" +
	"\x05start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"J\n" +
	"\x0eApproveRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x19\n" +
	"\bstaff_id\x18\x02 \x01(\tR\astaffId\"+\n" +
	"\x0fApproveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"_\n" +
	"\vDenyRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x19\n" +
	"\bstaff_id\x18\x02 \x01(\tR\astaffId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"(\n" +
	"\fDenyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"R\n" +
	"\x0fReassignRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12 \n" +
	"\fnew_staff_id\x18\x02 \x01(\tR\n" +
	"newStaffId\",\n" +
	"\x10ReassignResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x14GetAuditTrailRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"B\n" +
	"\x12AuditTrailResponse\x12,\n" +
	"\x06events\x18\x01 \x03(\v2\x14.approval.AuditEventR\x06events\"\xcc\x01\n" +
	"\n" +
	"AuditEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tR\tbookingId\x12\x19\n" +
	"\bstaff_id\x18\x03 \x01(\tR\astaffId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xfc\x02\n" +
	"\x0fApprovalService\x12J\n" +
	"\vListPending\x12\x1c.approval.ListPendingRequest\x1a\x1d.approval.ListPendingResponse\x12E\n" +
	"\x0eApproveBooking\x12\x18.approval.ApproveRequest\x1a\x19.approval.ApproveResponse\x12<\n" +
	"\vDenyBooking\x12\x15.approval.DenyRequest\x1a\x16.approval.DenyResponse\x12I\n" +
	"\x10ReassignApprover\x12\x19.approval.ReassignRequest\x1a\x1a.approval.ReassignResponse\x12M\n" +
	"\rGetAuditTrail\x12\x1e.approval.GetAuditTrailRequest\x1a\x1c.approval.AuditTrailResponseBGZEgithub.com/JJnvn/Software-Arch-CPRoom/backend/services/approval;protob\x06proto3"

var (
	file_approval_proto_rawDescOnce sync.Once
	file_approval_proto_rawDescData []byte
)

func file_approval_proto_rawDescGZIP() []byte {
	file_approval_proto_rawDescOnce.Do(func() {
		file_approval_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_approval_proto_rawDesc), len(file_approval_proto_rawDesc)))
	})
	return file_approval_proto_rawDescData
}

var file_approval_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_approval_proto_goTypes = []any{
	(*ListPendingRequest)(nil),    // 0: approval.ListPendingRequest
	(*ListPendingResponse)(nil),   // 1: approval.ListPendingResponse
	(*PendingBooking)(nil),        // 2: approval.PendingBooking
	(*ApproveRequest)(nil),        // 3: approval.ApproveRequest
	(*ApproveResponse)(nil),       // 4: approval.ApproveResponse
	(*DenyRequest)(nil),           // 5: approval.DenyRequest
	(*DenyResponse)(nil),          // 6: approval.DenyResponse
	(*ReassignRequest)(nil),       // 7: approval.ReassignRequest
	(*ReassignResponse)(nil),      // 8: approval.ReassignResponse
	(*GetAuditTrailRequest)(nil),  // 9: approval.GetAuditTrailRequest
	(*AuditTrailResponse)(nil),    // 10: approval.AuditTrailResponse
	(*AuditEvent)(nil),            // 11: approval.AuditEvent
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_approval_proto_depIdxs = []int32{
	2,  // 0: approval.ListPendingResponse.pending:type_name -> approval.PendingBooking
	12, // 1: approval.PendingBooking.start:type_name -> google.protobuf.Timestamp
	12, // 2: approval.PendingBooking.end:type_name -> google.protobuf.Timestamp
	11, // 3: approval.AuditTrailResponse.events:type_name -> approval.AuditEvent
	12, // 4: approval.AuditEvent.created_at:type_name -> google.protobuf.Timestamp
	0,  // 5: approval.ApprovalService.ListPending:input_type -> approval.ListPendingRequest
	3,  // 6: approval.ApprovalService.ApproveBooking:input_type -> approval.ApproveRequest
	5,  // 7: approval.ApprovalService.DenyBooking:input_type -> approval.DenyRequest
	7,  // 8: approval.ApprovalService.ReassignApprover:input_type -> approval.ReassignRequest
	9,  // 9: approval.ApprovalService.GetAuditTrail:input_type -> approval.GetAuditTrailRequest
	1,  // 10: approval.ApprovalService.ListPending:output_type -> approval.ListPendingResponse
	4,  // 11: approval.ApprovalService.ApproveBooking:output_type -> approval.ApproveResponse
	6,  // 12: approval.ApprovalService.DenyBooking:output_type -> approval.DenyResponse
	8,  // 13: approval.ApprovalService.ReassignApprover:output_type -> approval.ReassignResponse
	10, // 14: approval.ApprovalService.GetAuditTrail:output_type -> approval.AuditTrailResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_approval_proto_init() }
func file_approval_proto_init() {
	if File_approval_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_approval_proto_rawDesc), len(file_approval_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_approval_proto_goTypes,
		DependencyIndexes: file_approval_proto_depIdxs,
		MessageInfos:      file_approval_proto_msgTypes,
	}.Build()
	File_approval_proto = out.File
	file_approval_proto_goTypes = nil
	file_approval_proto_depIdxs = nil
}
