// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/booking.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Features      []string               `protobuf:"bytes,4,rep,name=features,proto3" json:"features,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRoomsRequest) Reset() {
	*x = SearchRoomsRequest{}
	mi := &file_proto_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRoomsRequest) ProtoMessage() {}

func (x *SearchRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRoomsRequest.ProtoReflect.Descriptor instead.
func (*SearchRoomsRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRoomsRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *SearchRoomsRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *SearchRoomsRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *SearchRoomsRequest) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *SearchRoomsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRoomsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Features      []string               `protobuf:"bytes,4,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_proto_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{1}
}

func (x *RoomInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomInfo) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *RoomInfo) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

type SearchRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomInfo            `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRoomsResponse) Reset() {
	*x = SearchRoomsResponse{}
	mi := &file_proto_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRoomsResponse) ProtoMessage() {}

func (x *SearchRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRoomsResponse.ProtoReflect.Descriptor instead.
func (*SearchRoomsResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRoomsResponse) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type GetRoomScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomScheduleRequest) Reset() {
	*x = GetRoomScheduleRequest{}
	mi := &file_proto_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomScheduleRequest) ProtoMessage() {}

func (x *GetRoomScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetRoomScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoomScheduleRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type RoomScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Bookings      []*BookingSummary      `protobuf:"bytes,2,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomScheduleResponse) Reset() {
	*x = RoomScheduleResponse{}
	mi := &file_proto_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomScheduleResponse) ProtoMessage() {}

func (x *RoomScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomScheduleResponse.ProtoReflect.Descriptor instead.
func (*RoomScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{4}
}

func (x *RoomScheduleResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomScheduleResponse) GetBookings() []*BookingSummary {
	if x != nil {
		return x.Bookings
	}
	return nil
}

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_proto_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBookingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBookingRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateBookingRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *CreateBookingRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type CreateBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingResponse) Reset() {
	*x = CreateBookingResponse{}
	mi := &file_proto_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingResponse) ProtoMessage() {}

func (x *CreateBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingResponse.ProtoReflect.Descriptor instead.
func (*CreateBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBookingResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CreateBookingResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBookingResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateBookingResponse) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *CreateBookingResponse) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_proto_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{7}
}

func (x *CancelBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type CancelBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingResponse) Reset() {
	*x = CancelBookingResponse{}
	mi := &file_proto_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingResponse) ProtoMessage() {}

func (x *CancelBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingResponse.ProtoReflect.Descriptor instead.
func (*CancelBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{8}
}

func (x *CancelBookingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	NewStart      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=new_start,json=newStart,proto3" json:"new_start,omitempty"`
	NewEnd        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=new_end,json=newEnd,proto3" json:"new_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingRequest) Reset() {
	*x = UpdateBookingRequest{}
	mi := &file_proto_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingRequest) ProtoMessage() {}

func (x *UpdateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *UpdateBookingRequest) GetNewStart() *timestamppb.Timestamp {
	if x != nil {
		return x.NewStart
	}
	return nil
}

func (x *UpdateBookingRequest) GetNewEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.NewEnd
	}
	return nil
}

type UpdateBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingResponse) Reset() {
	*x = UpdateBookingResponse{}
	mi := &file_proto_booking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingResponse) ProtoMessage() {}

func (x *UpdateBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingResponse.ProtoReflect.Descriptor instead.
func (*UpdateBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateBookingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TransferBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	NewOwnerId    string                 `protobuf:"bytes,2,opt,name=new_owner_id,json=newOwnerId,proto3" json:"new_owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferBookingRequest) Reset() {
	*x = TransferBookingRequest{}
	mi := &file_proto_booking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferBookingRequest) ProtoMessage() {}

func (x *TransferBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferBookingRequest.ProtoReflect.Descriptor instead.
func (*TransferBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{11}
}

func (x *TransferBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *TransferBookingRequest) GetNewOwnerId() string {
	if x != nil {
		return x.NewOwnerId
	}
	return ""
}

type TransferBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferBookingResponse) Reset() {
	*x = TransferBookingResponse{}
	mi := &file_proto_booking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferBookingResponse) ProtoMessage() {}

func (x *TransferBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferBookingResponse.ProtoReflect.Descriptor instead.
func (*TransferBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{12}
}

func (x *TransferBookingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AdminListBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListBookingsRequest) Reset() {
	*x = AdminListBookingsRequest{}
	mi := &file_proto_booking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListBookingsRequest) ProtoMessage() {}

func (x *AdminListBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListBookingsRequest.ProtoReflect.Descriptor instead.
func (*AdminListBookingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{13}
}

func (x *AdminListBookingsRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type AdminListBookingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*BookingSummary      `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListBookingsResponse) Reset() {
	*x = AdminListBookingsResponse{}
	mi := &file_proto_booking_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListBookingsResponse) ProtoMessage() {}

func (x *AdminListBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListBookingsResponse.ProtoReflect.Descriptor instead.
func (*AdminListBookingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{14}
}

func (x *AdminListBookingsResponse) GetBookings() []*BookingSummary {
	if x != nil {
		return x.Bookings
	}
	return nil
}

type BookingSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingSummary) Reset() {
	*x = BookingSummary{}
	mi := &file_proto_booking_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingSummary) ProtoMessage() {}

func (x *BookingSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingSummary.ProtoReflect.Descriptor instead.
func (*BookingSummary) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{15}
}

func (x *BookingSummary) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *BookingSummary) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BookingSummary) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *BookingSummary) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *BookingSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_booking_proto protoreflect.FileDescriptor

const file_proto_booking_proto_rawDesc = "" +
	"\n" +
	"\x13proto/booking.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\x01\n" +
	"\x12SearchRoomsRequest\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12\x1a\n" +
	"\bfeatures\x18\x04 \x03(\tR\bfeatures\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"o\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12\x1a\n" +
	"\bfeatures\x18\x04 \x03(\tR\bfeatures\"<\n" +
	"\x13SearchRoomsResponse\x12%\n" +
	"\x05rooms\x18\x01 \x03(\v2\x0f.proto.RoomInfoR\x05rooms\"1\n" +
	"\x16GetRoomScheduleRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"b\n" +
	"\x14RoomScheduleResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x121\n" +
	"\bbookings\x18\x02 \x03(\v2\x15.proto.BookingSummaryR\bbookings\"\xa8\x01\n" +
	"\x14CreateBookingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x120\n" +
	"\x05start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\xc8\x01\n" +
	"\x15CreateBookingResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x120\n" +
	"\x05start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"5\n" +
	"\x14CancelBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"1\n" +
	"\x15CancelBookingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa3\x01\n" +
	"\x14UpdateBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x127\n" +
	"\tnew_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bnewStart\x123\n" +
	"\anew_end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06newEnd\"1\n" +
	"\x15UpdateBookingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Y\n" +
	"\x16TransferBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12 \n" +
	"\fnew_owner_id\x18\x02 \x01(\tR\n" +
	"newOwnerId\"3\n" +
	"\x17TransferBookingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x18AdminListBookingsRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"N\n" +
	"\x19AdminListBookingsResponse\x121\n" +
	"\bbookings\x18\x01 \x03(\v2\x15.proto.BookingSummaryR\bbookings\"\xc0\x01\n" +
	"\x0eBookingSummary\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x120\n" +
	"\x05start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status2\xb3\x04\n" +
	"\x0eBookingService\x12D\n" +
	"\vSearchRooms\x12\x19.proto.SearchRoomsRequest\x1a\x1a.proto.SearchRoomsResponse\x12M\n" +
	"\x0fGetRoomSchedule\x12\x1d.proto.GetRoomScheduleRequest\x1a\x1b.proto.RoomScheduleResponse\x12J\n" +
	"\rCreateBooking\x12\x1b.proto.CreateBookingRequest\x1a\x1c.proto.CreateBookingResponse\x12J\n" +
	"\rCancelBooking\x12\x1b.proto.CancelBookingRequest\x1a\x1c.proto.CancelBookingResponse\x12J\n" +
	"\rUpdateBooking\x12\x1b.proto.UpdateBookingRequest\x1a\x1c.proto.UpdateBookingResponse\x12P\n" +
	"\x0fTransferBooking\x12\x1d.proto.TransferBookingRequest\x1a\x1e.proto.TransferBookingResponse\x12V\n" +
	"\x11AdminListBookings\x12\x1f.proto.AdminListBookingsRequest\x1a .proto.AdminListBookingsResponseBFZDgithub.com/JJnvn/Software-Arch-CPRoom/backend/services/booking;protob\x06proto3"

var (
	file_proto_booking_proto_rawDescOnce sync.Once
	file_proto_booking_proto_rawDescData []byte
)

func file_proto_booking_proto_rawDescGZIP() []byte {
	file_proto_booking_proto_rawDescOnce.Do(func() {
		file_proto_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_booking_proto_rawDesc), len(file_proto_booking_proto_rawDesc)))
	})
	return file_proto_booking_proto_rawDescData
}

var file_proto_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_booking_proto_goTypes = []any{
	(*SearchRoomsRequest)(nil),        // 0: proto.SearchRoomsRequest
	(*RoomInfo)(nil),                  // 1: proto.RoomInfo
	(*SearchRoomsResponse)(nil),       // 2: proto.SearchRoomsResponse
	(*GetRoomScheduleRequest)(nil),    // 3: proto.GetRoomScheduleRequest
	(*RoomScheduleResponse)(nil),      // 4: proto.RoomScheduleResponse
	(*CreateBookingRequest)(nil),      // 5: proto.CreateBookingRequest
	(*CreateBookingResponse)(nil),     // 6: proto.CreateBookingResponse
	(*CancelBookingRequest)(nil),      // 7: proto.CancelBookingRequest
	(*CancelBookingResponse)(nil),     // 8: proto.CancelBookingResponse
	(*UpdateBookingRequest)(nil),      // 9: proto.UpdateBookingRequest
	(*UpdateBookingResponse)(nil),     // 10: proto.UpdateBookingResponse
	(*TransferBookingRequest)(nil),    // 11: proto.TransferBookingRequest
	(*TransferBookingResponse)(nil),   // 12: proto.TransferBookingResponse
	(*AdminListBookingsRequest)(nil),  // 13: proto.AdminListBookingsRequest
	(*AdminListBookingsResponse)(nil), // 14: proto.AdminListBookingsResponse
	(*BookingSummary)(nil),            // 15: proto.BookingSummary
	(*timestamppb.Timestamp)(nil),     // 16: google.protobuf.Timestamp
}
var file_proto_booking_proto_depIdxs = []int32{
	16, // 0: proto.SearchRoomsRequest.start:type_name -> google.protobuf.Timestamp
	16, // 1: proto.SearchRoomsRequest.end:type_name -> google.protobuf.Timestamp
	1,  // 2: proto.SearchRoomsResponse.rooms:type_name -> proto.RoomInfo
	15, // 3: proto.RoomScheduleResponse.bookings:type_name -> proto.BookingSummary
	16, // 4: proto.CreateBookingRequest.start:type_name -> google.protobuf.Timestamp
	16, // 5: proto.CreateBookingRequest.end:type_name -> google.protobuf.Timestamp
	16, // 6: proto.CreateBookingResponse.start:type_name -> google.protobuf.Timestamp
	16, // 7: proto.CreateBookingResponse.end:type_name -> google.protobuf.Timestamp
	16, // 8: proto.UpdateBookingRequest.new_start:type_name -> google.protobuf.Timestamp
	16, // 9: proto.UpdateBookingRequest.new_end:type_name -> google.protobuf.Timestamp
	15, // 10: proto.AdminListBookingsResponse.bookings:type_name -> proto.BookingSummary
	16, // 11: proto.BookingSummary.start:type_name -> google.protobuf.Timestamp
	16, // 12: proto.BookingSummary.end:type_name -> google.protobuf.Timestamp
	0,  // 13: proto.BookingService.SearchRooms:input_type -> proto.SearchRoomsRequest
	3,  // 14: proto.BookingService.GetRoomSchedule:input_type -> proto.GetRoomScheduleRequest
	5,  // 15: proto.BookingService.CreateBooking:input_type -> proto.CreateBookingRequest
	7,  // 16: proto.BookingService.CancelBooking:input_type -> proto.CancelBookingRequest
	9,  // 17: proto.BookingService.UpdateBooking:input_type -> proto.UpdateBookingRequest
	11, // 18: proto.BookingService.TransferBooking:input_type -> proto.TransferBookingRequest
	13, // 19: proto.BookingService.AdminListBookings:input_type -> proto.AdminListBookingsRequest
	2,  // 20: proto.BookingService.SearchRooms:output_type -> proto.SearchRoomsResponse
	4,  // 21: proto.BookingService.GetRoomSchedule:output_type -> proto.RoomScheduleResponse
	6,  // 22: proto.BookingService.CreateBooking:output_type -> proto.CreateBookingResponse
	8,  // 23: proto.BookingService.CancelBooking:output_type -> proto.CancelBookingResponse
	10, // 24: proto.BookingService.UpdateBooking:output_type -> proto.UpdateBookingResponse
	12, // 25: proto.BookingService.TransferBooking:output_type -> proto.TransferBookingResponse
	14, // 26: proto.BookingService.AdminListBookings:output_type -> proto.AdminListBookingsResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_booking_proto_init() }
func file_proto_booking_proto_init() {
	if File_proto_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_booking_proto_rawDesc), len(file_proto_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_booking_proto_goTypes,
		DependencyIndexes: file_proto_booking_proto_depIdxs,
		MessageInfos:      file_proto_booking_proto_msgTypes,
	}.Build()
	File_proto_booking_proto = out.File
	file_proto_booking_proto_goTypes = nil
	file_proto_booking_proto_depIdxs = nil
}
